### ISSUE TITLE
Playback failing due to incorrect URL

### ISSUE THREAD

**Issue by IsoLinearCHiP** [videoparty/prime-chrome#27]
Hi, I just tryed out the extension, and kept getting a something went wrong page from amazon. (with various pictures of dogs ;) )

After comparing the pages the extension redirects to with the URLs generated by amazon it seems as though the path is missing `/gp/video`.

After correcting the generated URLs and adding `/gp/video` manually before `/detail` it seemed to work again.

https://github.com/videoparty/prime-chrome/blob/d6f405c4942e38fda681e4647a96fa3986c1f1fd/src/contentscripts/listener/websocket.js#L230

I used the developer tools to monkey patch the referenced line above to:

`window.location.href = urlBase + '/gp/video/detail/' + data.videoId + '/ref=' + data.ref + '?autoplay=1&t=' + startTime;`

which seemed to have solved the issue.

This is on amazon.de, in case its a region specific problem.

**Comment by marnixbent** [comment]
Thanks for the bug report! This is indeed the case for amazon.com websites, not primevideo.com. Will push a fix right away 👍

**Comment by marnixbent** [comment]
Fix (v0.6.2) is published in the Chrome webstore
